@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue May 14 15:29:05 +0200 2024
REM SW Build 4126759 on Thu Feb  8 23:53:51 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim uart_block_wrapper_behav -key {Behavioral:sim_1:Functional:uart_block_wrapper} -tclbatch uart_block_wrapper.tcl -protoinst "protoinst_files/uart_block.protoinst" -log simulate.log"
call xsim  uart_block_wrapper_behav -key {Behavioral:sim_1:Functional:uart_block_wrapper} -tclbatch uart_block_wrapper.tcl -protoinst "protoinst_files/uart_block.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
