# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/mads/Documents/4.semester/DIgitilSystemDesign/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/test/test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test || ORIG_REF_NAME==test} -quiet] -quiet

# IP: bd/test/ip/test_comparator_0_0/test_comparator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_comparator_0_0 || ORIG_REF_NAME==test_comparator_0_0} -quiet] -quiet

# IP: bd/test/ip/test_spi_slave_0_0/test_spi_slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spi_slave_0_0 || ORIG_REF_NAME==test_spi_slave_0_0} -quiet] -quiet

# IP: bd/test/ip/test_xlconstant_0_0/test_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_xlconstant_0_0 || ORIG_REF_NAME==test_xlconstant_0_0} -quiet] -quiet

# IP: bd/test/ip/test_xlconstant_1_0/test_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_xlconstant_1_0 || ORIG_REF_NAME==test_xlconstant_1_0} -quiet] -quiet

# XDC: /home/mads/Documents/4.semester/DIgitilSystemDesign/PRO4/PRO4.gen/sources_1/bd/test/test_ooc.xdc
