# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/aksel/OneDrive/Skrivebord/4-semester/DigitalProgrammerbarElektronik/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/pwm_block/pwm_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_block || ORIG_REF_NAME==pwm_block} -quiet] -quiet

# IP: bd/pwm_block/ip/pwm_block_counter_0_0/pwm_block_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_block_counter_0_0 || ORIG_REF_NAME==pwm_block_counter_0_0} -quiet] -quiet

# IP: bd/pwm_block/ip/pwm_block_comparator_0_0/pwm_block_comparator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_block_comparator_0_0 || ORIG_REF_NAME==pwm_block_comparator_0_0} -quiet] -quiet

# IP: bd/pwm_block/ip/pwm_block_xlconstant_1_0/pwm_block_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_block_xlconstant_1_0 || ORIG_REF_NAME==pwm_block_xlconstant_1_0} -quiet] -quiet

# IP: bd/pwm_block/ip/pwm_block_clk_divider_0_0/pwm_block_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_block_clk_divider_0_0 || ORIG_REF_NAME==pwm_block_clk_divider_0_0} -quiet] -quiet

# IP: bd/pwm_block/ip/pwm_block_demultiplexer_1x2_0_2/pwm_block_demultiplexer_1x2_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_block_demultiplexer_1x2_0_2 || ORIG_REF_NAME==pwm_block_demultiplexer_1x2_0_2} -quiet] -quiet

# IP: bd/pwm_block/ip/pwm_block_xlconstant_2_0/pwm_block_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_block_xlconstant_2_0 || ORIG_REF_NAME==pwm_block_xlconstant_2_0} -quiet] -quiet

# IP: bd/pwm_block/ip/pwm_block_d_latch_0_0/pwm_block_d_latch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_block_d_latch_0_0 || ORIG_REF_NAME==pwm_block_d_latch_0_0} -quiet] -quiet

# IP: bd/pwm_block/ip/pwm_block_btn_pwn_inc_0_0/pwm_block_btn_pwn_inc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_block_btn_pwn_inc_0_0 || ORIG_REF_NAME==pwm_block_btn_pwn_inc_0_0} -quiet] -quiet

# XDC: c:/Users/aksel/OneDrive/Skrivebord/4-semester/DigitalProgrammerbarElektronik/Lab4/lab4project.gen/sources_1/bd/pwm_block/pwm_block_ooc.xdc
