@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Mar 21 13:58:27 +0100 2024
REM SW Build 4126759 on Thu Feb  8 23:53:51 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim btn_pwn_inc_behav -key {Behavioral:sim_1:Functional:btn_pwn_inc} -tclbatch btn_pwn_inc.tcl -protoinst "protoinst_files/pwm_block.protoinst" -protoinst "protoinst_files/light.protoinst" -log simulate.log"
call xsim  btn_pwn_inc_behav -key {Behavioral:sim_1:Functional:btn_pwn_inc} -tclbatch btn_pwn_inc.tcl -protoinst "protoinst_files/pwm_block.protoinst" -protoinst "protoinst_files/light.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
